### ISSUE TITLE
PCLMockCodeGen.exe method generation bug.

### ISSUE THREAD

**Issue by elwray** [kentcb/PCLMock#14]
Hi, developers!

I use PCLMockCodeGen.exe tool for generate mocks. When code was generated I found the next error in my Mocks.cs file:

``` csharp
public System.Double ToDisplayX(System.Double x)
{
    return this.Apply(x => x.ToDisplayX(x));
}
```

As you can see, PCLMockCodeGen tool generate param in anonymous method with "x" name, but my function argument already have "x" name. In this case Visual Studio shows error and this code can not be compiled.

**Comment by kentcb** [comment]
Thanks for the report @El-Wray - I'll take a look when I next can.
