### ISSUE TITLE
PCLMockCodeGen.exe interface with event generation bug.

### ISSUE THREAD

**Issue by elwray** [kentcb/PCLMock#15]
Hi, developers!

I use PCLMockCodeGen.exe tool for generate mocks. When code was generated I found that tool not generated code for event in my interface:

``` csharp
public interface IProductLicenseService
{
   event LicenseChangedEventHandler LicenseChanged;
}
```

**Comment by kentcb** [comment]
Hi,

Per [the docs](https://github.com/kentcb/PCLMock/blob/master/Doc/defining-mocks.md#events), events are not currently mockable. Thus, the code generator does not generate anything for them. However, you can always supplement the generated code with a partial class that defines the event in whatever way makes sense for you.
