### ISSUE TITLE
Consider opening up loose behavior to consumers

### ISSUE THREAD

**Issue by kentcb** [kentcb/PCLMock#19]
Per #18, give some thought to whether it is possible+desirable to open up the loose behavior "pipeline" to consuming code. That is, allow client code to make sweeping decisions about loose behavior such as "for any method returning `Task<T>`, return `Task.FromResult(default(T))` by default".
- [x] Define a hook interface (`ISomethingSomething`) in codegen assembly (also: consider an altogether separate SDK assembly)
- [x] Add the requisite functionality to the configuration, such that hooks can be configured
- [x] Have the code generator utilise the hooks when generating mocks
- [x] Write two standard hooks: one for TPL-based async members, and one for Rx-based async members
- [x] Update the default configuration file to include these standard hooks by default
- [x] Create new NuGet package: `PCLMock.CodeGeneration` that includes only the codegen assembly

**Comment by kensykora** [comment]
IMO, simply handling async/await functionality is important for loose mock behavior given that async/await are keywords and are as important to test as normal behavior. You brought up the point of Observables in #18, but as far as I know there are no specific C# language keywords that interact with observables the way that async/await interacts with Task classes. Given this strong integration with C#, i feel like Loose behavior should return a Task<T> for undefined behaviors rather than just null

**Comment by kentcb** [comment]
Yes, observables can be used for asynchrony, and they offer some benefits over using tasks (particularly testability). I take your point though, and will bear this in mind.

**Comment by kentcb** [comment]
OK, this is done (_phew_ - was painful!)

There is an `IPlugin` interface that can be implemented by code generation plugins. They are configured via an XML configuration file.

PCLMock has two plugin implementations:
- `TaskBasedAsynchrony`
- `ObservableBasedAsynchrony`

They generate default specifications for mocks that use either `Task` / `Task<T>`, or `IObservable<T>` respectively.

The only aspect of this I'm not 100% certain on is the specifications generated for observables. This is because the semantics of observables cannot be determined from the type alone. In the end I decided that properties returning observables have collection semantics (and an empty observable is returned by default) and methods returning observables have asynchronous invocation semantics (and an observable ticking a single item of type `T` is returned). Time will tell (during the alpha) whether this is good enough.
