### ISSUE TITLE
netstandard/netcore

### ISSUE THREAD

**Issue by kentcb** [kentcb/PCLMock#31]
V5 of PCLMock will (hopefully) be netstandard/netcore. This is a checklist of stuff I need to do/problems I need to solve for that to happen.

- [x] Source gen
  - [x] Consider _all_ symbols, not just those in the project in which generation is instigated (actually, pretty sure this is not possible with C# Source Generators, but trying to confirm. **If not, remember to simplify the symbol enumeration logic so that it doesn't crawl all dependencies**).
  - [x] Forward diagnostics (errors/warnings) onto the compiler
  - [x] Is there a sensible way I could make debugging easier by exposing the log under strict circumstances? No, not really :(
- [x] Reinstate console generator
  - [x] Likely need generator to accept an enumeration of compilations from which to generate mocks. Console generator can pass in compilations from all solution projects.
  - [x] Forward Buildalyzer logs on appropriately
- [x] Retire T4 generator?
- [x] Improve logging infrastructure and log messages
- [x] Modernize build scripts
  - [x] Cake
  - [x] NuGet packaging done via MSBuild
- [ ] Update docs

---

**All these notes are old, but just keeping them around in case I need to refer to them.**

Here is a [useful reference](http://www.natemcmaster.com/blog/2017/11/11/build-tools-in-nuget/) on creating a NuGet package for the console runner.

Another [useful reference](https://www.thomaslevesque.com/2017/11/13/transform-t4-templates-as-part-of-the-build-and-pass-variables-from-the-project/) with respect to executing T4 templates in an SDK-style csproj.

UPDATE (24/05/18): had another crack at this using Buildalyzer and am giving up in frustration again. I was able to move the code base in the right direction (reinstating tests, for example), but ultimately wasn't able to progress with the _actual_ problem. I need to record this because I'll otherwise forget. These are the problems I'm noticing:

1. Types that are referenced by the target code don't resolve correctly unless they're core (already referenced) types. For example, if the target code uses NodaTime, all NodaTime types won't be qualified in the generated code.
2. In attempting to address point 1, I figured it was because referenced assemblies weren't being loaded correctly into the `Project` instances. Indeed, that looks like it might be the case. On a hunch, I tried doing a `dotnet restore` against the target project before running the generator again, but this results in an exception (see below)

```
System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added. Key: Microsoft.CodeAnalysis.CSharp.CSharpCompilationReference
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__30.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<BuildCompilationInfoFromScratchAsync>d__24.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetOrBuildCompilationInfoAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetCompilationSlowAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PCLMock.CodeGeneration.Generator.<>c__DisplayClass3_0.<<GenerateMocksAsync>b__0>d.MoveNext() in C:\Users\kent\Repository\PCLMock\Src\PCLMock.CodeGeneration\Generator.cs:line 77
```

UPDATE (06/07/18): I've successfully reproduced the above problem and submitted a bug report [here](https://github.com/dotnet/roslyn/issues/27558).

**Comment by velocitysystems** [comment]
+1. We have recently upgraded some PCL projects to .NET Standard and this means we are unable to use the T4 template code generation.

We love PCLMock, so very keen to see it support .NET Standard.

**Comment by kentcb** [comment]
Potentially unblocked by [Buildalyzer](https://github.com/daveaglick/Buildalyzer). Need to try it to see.

**Comment by curtisshipley** [comment]
Hi Kent. What can we do to help getting this working on .net standard 2.0? If you have anything that needs looking at, I'd be happy to pitch in.

**Comment by kentcb** [comment]
Hey @curtisshipley - thanks for your offer.

At this point, I'm relying on Buildalyzer to work seamlessly. I actually have codegen working again, but there are a few quirks with Buildalyzer that make the experience less than stellar (primarily, having to delete all `obj` directories first which I reported [here](https://github.com/daveaglick/Buildalyzer/issues/28)). If I had more time, I'd be looking to solve these Buildalyzer issues and PR'ing them, so if you want to take a stab at that, I would certainly appreciate it (and I'm sure @daveaglick would too!).

**Comment by curtisshipley** [comment]
I can take a look. What code do I need to grab/run to repro this?

**Comment by kentcb** [comment]
You'll need the `netstandard` branch of PCLMock. Configure the console runner to execute a target solution that uses SDK-style csproj. You should see errors trying to generate mocks when the target solution is already built, but not if you clear out the `obj` directories.

Also, I attached a sample target solution to the Buildalyzer issue, so you can just grab that.

**Comment by daveaglick** [comment]
@curtisshipley It'd be awesome if you were able to make some progress on the Buildalyzer issue. There isn't a ton of code there - Buildalyzer basically just bootstraps the MSBuild API so we can run a design-time build (I.e., evaluate the project file up to the point of calling the compiler and then stopping before we actually compile the code).

I'm also planning on taking a look at the Buildalyzer block soon too so hopefully between us we can make some progress.

**Comment by karlingen** [comment]
Is there anything we can do to help out?

**Comment by pellet** [comment]
Hey Kent,
I seem to have gotten PCLMock generating my mocks fine on macOS with the console tool.
I made a few changes to your .netstandard branch namely:
Added some nuget packages as dependencies.
Upgraded buildalyzer to v1.
Had to remove the .AddReference calls from the plugins, they were somehow corrupting the compilation object and it would lose its ability to resolve types, in some instances it couldn't even resolve "System.String".  I'm not sure if these calls are needed anyway? At least they don't seem to be needed for my projects.
I managed to get the T4 project to link against the codegenerator project by upgrading it to .net471 as well.
I'd prefer using the console tool since T4 doesn't work on macOS however it might work ok as long as a NuGet.Config is used to place the packages into the packages directory.

**Comment by pellet** [comment]
Would you like me to open some small pull requests to get this closer to working with .netstandard? Things should work a lot better now with Builalyzer 2.0.

**Comment by kentcb** [comment]
I've been meaning to try Buildalyzer 2.0, but just haven't had the chance yet. tbh, I'm not holding me breath because I actually hit a Roslyn bug (linked in the description) that I _still_ haven't heard back on.

**Comment by pellet** [comment]
Ok is this in relation to the `compilation.AddReferences` calls? I noticed some issues with them in .netcore so I removed the calls then the code generation worked fine for my solution.

**Comment by kentcb** [comment]
If they were removed, I doubt the plugins were producing correct code.

**Comment by pellet** [comment]
The plugins actually worked fine for me without needing the calls, the references were brought in implicitly by my apps' solution.

**Comment by kentcb** [comment]
Might be something to do with running on Mac then? I'm using Windows. Don't suppose you've got a Windows machine handy?

**Comment by pellet** [comment]
Could be, yeah I use windows in a vm(parallels) when needed, if you have a sample project with the issue I can take a look and see if I can find a workaround.

**Comment by pellet** [comment]
My workmate has ran our generator on windows and it worked ok for him.

**Comment by pellet** [comment]
Hey Kent, which symbols are not resolving for you when you use the generator? Give a try of my forked netstandard branch and see if it works for you like it does for me.
