### ISSUE TITLE
Issues with mocking a method to throw an exception

### ISSUE THREAD

**Issue by Medality** [kentcb/PCLMock#33]
Hi,

I found two annoying issues when mocking a method to throw an exception:

1. When doing the following, the exception is thrown but "called" will stay false:
`bool called = false;`
`mock.When(x => x.SomeMethod()).Do(() => called = true).Throw()`
`try { mock.SomeMethod(); }`
`catch { }`
2. When throwing an exception in the Do action, it will be wrapped under a TargetInvocationException:
`mock.When(x => x.SomeMethod()).Do(() => throw new MyException())`
`try { mock.SomeMethod(); }`
`catch (MyException) { /* Will never go there. */ }`
`catch (TargetInvocationException) { /* Will go there instead. */ }`

Thanks for all the nice work!

**Comment by kentcb** [comment]
Thanks for the report @Medality. Just wanted to note that I will certainly look into these issues, but not until #31 is unblocked and done.

**Comment by kentcb** [comment]
Sorry it took so long @Medality, and you were spot on in both cases. I've fixed this in #41.
